project_id = "ptsrzvbrvopdjtgtstzg"

[functions.yookassa-create-payment]
verify_jwt = false

[functions.yookassa-webhook]
verify_jwt = false

[functions.get-download-url]
verify_jwt = false

[functions.resend-test]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.send-payment-reminder]
verify_jwt = false

[functions.admin-send-email]
verify_jwt = false

[functions.send-contact-message]
verify_jwt = false